[global]
q = "exit"
Up = "move_up"
Down = "move_down"
j = "move_down"
k = "move_up"
Ctrl-p = "open_process"

[file_panel]
h = "go_parent"
l = "open_entry"
Tab = "focus_sidebar"
Enter = "open_entry"
Right = "open_entry"
Left = "go_parent"
"." = "show_hidden_files"
m = "focus_metadata"
e = "open_editor"
n = "new_entry"
d = "delete_entry"
y = "copy_entry"
Y = "remove_entry_clipboard"
c = "focus_clipboard"
p = "add_copy_process"

[sidebar]
h = "focus_files"
Tab = "focus_files"
l = "open_bookmark"
Right = "open_bookmark"
Enter = "open_bookmark"

[metadata]
Esc = "exit_metadata"
y = "copy_metadata"
Space = "copy_metadata"

# -------------------------
# ----- Create Mode
# -------------------------
[create]
Esc = "cancel_create"
Enter = "confirm_create"
Left = "move_cursor_left"
Right = "move_cursor_right"
Backspace = "delete_char"

# -------------------------
# ----- File Clipboard Mode
# -------------------------

[file_clipboard]
Esc = "exit_clipboard"
d = "remove_entry"
c = "clear_clipboard"

# -------------------------
# ----- Process Mode
# -------------------------

[process]
Esc = "exit_process"
Ctrl-c = "cancel_process"
c = "cancel_process"

[delete]
Esc = "cancel_delete"
Enter = "confirm_delete"
