[global]
q = "exit"
Up = "move_up"
Down = "move_down"

[file_panel]
f = "focus_sidebar"
Right = "open_entry"
Enter = "open_entry"
Left = "go_to_parent_dir"
m = "focus_metadata"
e = "open_editor"
n = "open_create_panel"
Ctrl-c = "add_entry_clipboard"
Ctrl-Alt-c = "focus_file_clipboard"

# -------------------------
# ----- SideBar Mode
# -------------------------
[sidebar]
f = "focus_file_panel"
Right = "open_bookmark"
Enter = "open_bookmark"

# -------------------------
# ----- Metadata Mode
# -------------------------
[metadata]
f = "exit_metadata"
Space = "copy_metadata"

# -------------------------
# ----- Create Mode
# -------------------------
[create]
Esc = "cancel_create"
Enter = "confirm_create"
Left = "move_input_cursor_left"
Right = "move_input_cursor_right"
Backspace = "remove_input_char"

# -------------------------
# ----- File Clipboard Mode
# -------------------------

[file_clipboard]
Esc = "exit_file_clipboard"
d = "remove_entry_file_clipboard"
a = "clear_file_clipboard"
